In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  1.5846e+29  0.0000e+00
 1.5846e+29  7.0065e-45  1.1614e-41
 0.0000e+00  2.2369e+08  0.0000e+00
 0.0000e+00  2.1524e-42  2.1524e-42
        nan         nan -2.5151e-24
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [4]:
x = torch.rand(5, 3)
print(x)


 0.9086  0.5463  0.6116
 0.4133  0.9602  0.1336
 0.0148  0.6892  0.1193
 0.1254  0.0220  0.1548
 0.0251  0.5584  0.6880
[torch.FloatTensor of size 5x3]



Get its size



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.0776  0.5951  1.0732
 1.1327  1.0474  0.7800
 0.9649  1.4813  1.0629
 0.4919  0.5567  0.7084
 0.3334  0.8928  1.6540
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 1.0776  0.5951  1.0732
 1.1327  1.0474  0.7800
 0.9649  1.4813  1.0629
 0.4919  0.5567  0.7084
 0.3334  0.8928  1.6540
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.0776  0.5951  1.0732
 1.1327  1.0474  0.7800
 0.9649  1.4813  1.0629
 0.4919  0.5567  0.7084
 0.3334  0.8928  1.6540
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 1.0776  0.5951  1.0732
 1.1327  1.0474  0.7800
 0.9649  1.4813  1.0629
 0.4919  0.5567  0.7084
 0.3334  0.8928  1.6540
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1])


 0.5463
 0.9602
 0.6892
 0.0220
 0.5584
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [13]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y